<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cari berdasarkan skill</name>
   <tag></tag>
   <elementGuidId>ee63d4df-3e1d-4c0b-9e39-481ebc7a6ed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-searchSkill-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-searchSkill-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f51f43c7-f304-4bf1-9903-9dce7157a6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ac859ea9-126e-45e1-b731-3c61d7d4a0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-searchSkill-container</value>
      <webElementGuid>4b6e2c96-473e-436b-a3cf-ea5c3ac6d2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7932ec32-2d0d-4ae3-b6a8-fc86553b94ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e797bdf9-cef6-4aaf-a52b-356c590da13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cari berdasarkan skill</value>
      <webElementGuid>24135237-f881-4bc9-97d0-150a4675c0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari berdasarkan skill</value>
      <webElementGuid>307c1e64-f73c-4a91-8311-018d25097ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-searchSkill-container&quot;)</value>
      <webElementGuid>7fd31e7c-4017-4aaf-88b6-5e2de3fc99aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-searchSkill-container']</value>
      <webElementGuid>f7bf7277-33ed-4676-9750-e0dd4da56712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari berdasarkan posisi'])[1]/following::span[6]</value>
      <webElementGuid>81f93bc0-0faf-4d87-8c8a-ec392335b4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talent'])[4]/following::span[11]</value>
      <webElementGuid>dedb950b-9208-4230-9a9c-f1156e76d03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status:'])[1]/preceding::span[4]</value>
      <webElementGuid>565d91a5-c09b-48b2-8247-06541529ee7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/span</value>
      <webElementGuid>af0b59e2-c0d4-4e6f-859b-818986a485d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-searchSkill-container' and @title = 'Cari berdasarkan skill' and (text() = 'Cari berdasarkan skill' or . = 'Cari berdasarkan skill')]</value>
      <webElementGuid>0534c314-e01e-4201-8e38-58043a2536ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
